server.port=${SERVER_PORT:8082}
spring.application.name=carniceria-api-gateway

spring.cloud.gateway.routes[0].id=pedidos-service
spring.cloud.gateway.routes[0].uri=${ORDERS_SERVICE_URL:http://orders-service:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.routes[1].id=backend-service
spring.cloud.gateway.routes[1].uri=${BACKEND_SERVICE_URL:http://backend:8080}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=${CORS_ALLOWED_ORIGINS:http://localhost,http://18.230.85.195}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

management.endpoints.web.exposure.include=health,info
