spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:parcial_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:parcial_user}
    password: ${DB_PASSWORD:parcial2026}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost,http://18.230.85.195}
  audit:
    datasource:
      url: jdbc:postgresql://${AUDIT_DB_HOST:postgres}:${AUDIT_DB_PORT:5432}/${AUDIT_DB_NAME:parcial_audit}
      username: ${AUDIT_DB_USER:audit_user}
      password: ${AUDIT_DB_PASSWORD:audit2026}
